// Code generated by Kitex v0.7.3. DO NOT EDIT.

package hello

import (
	server "github.com/cloudwego/kitex/server"
	service "kitex_study/kitex_gen/kitex_gen/service"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler service.Hello, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
