// Code generated by Kitex v0.7.3. DO NOT EDIT.
package hello

import (
	server "github.com/cloudwego/kitex/server"
	service "kitex_study/kitex_gen/kitex_gen/service"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler service.Hello, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
